/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayRegisterParams
 */
export interface EmaopayRegisterParams {
    /**
     * 
     * @type {string}
     * @memberof EmaopayRegisterParams
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof EmaopayRegisterParams
     */
    username?: string;
}

/**
 * Check if a given object implements the EmaopayRegisterParams interface.
 */
export function instanceOfEmaopayRegisterParams(value: object): boolean {
    return true;
}

export function EmaopayRegisterParamsFromJSON(json: any): EmaopayRegisterParams {
    return EmaopayRegisterParamsFromJSONTyped(json, false);
}

export function EmaopayRegisterParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayRegisterParams {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function EmaopayRegisterParamsToJSON(value?: EmaopayRegisterParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'password': value['password'],
        'username': value['username'],
    };
}

