/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayDeleteQrCodeParams
 */
export interface EmaopayDeleteQrCodeParams {
    /**
     * 
     * @type {Array<string>}
     * @memberof EmaopayDeleteQrCodeParams
     */
    ids?: Array<string>;
}

/**
 * Check if a given object implements the EmaopayDeleteQrCodeParams interface.
 */
export function instanceOfEmaopayDeleteQrCodeParams(value: object): boolean {
    return true;
}

export function EmaopayDeleteQrCodeParamsFromJSON(json: any): EmaopayDeleteQrCodeParams {
    return EmaopayDeleteQrCodeParamsFromJSONTyped(json, false);
}

export function EmaopayDeleteQrCodeParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayDeleteQrCodeParams {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
    };
}

export function EmaopayDeleteQrCodeParamsToJSON(value?: EmaopayDeleteQrCodeParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ids': value['ids'],
    };
}

