/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayMerchant
 */
export interface EmaopayMerchant {
    /**
     * 
     * @type {Date}
     * @memberof EmaopayMerchant
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EmaopayMerchant
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof EmaopayMerchant
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof EmaopayMerchant
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EmaopayMerchant
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof EmaopayMerchant
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof EmaopayMerchant
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof EmaopayMerchant
     */
    userId?: string;
}

/**
 * Check if a given object implements the EmaopayMerchant interface.
 */
export function instanceOfEmaopayMerchant(value: object): boolean {
    return true;
}

export function EmaopayMerchantFromJSON(json: any): EmaopayMerchant {
    return EmaopayMerchantFromJSONTyped(json, false);
}

export function EmaopayMerchantFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayMerchant {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
        'name': json['name'] == null ? undefined : json['name'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function EmaopayMerchantToJSON(value?: EmaopayMerchant | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'description': value['description'],
        'id': value['id'],
        'key': value['key'],
        'name': value['name'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'userId': value['userId'],
    };
}

