/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayCredentials
 */
export interface EmaopayCredentials {
    /**
     * 临时证书密钥ID
     * @type {string}
     * @memberof EmaopayCredentials
     */
    tmpSecretId?: string;
    /**
     * 临时证书密钥Key
     * @type {string}
     * @memberof EmaopayCredentials
     */
    tmpSecretKey?: string;
    /**
     * token
     * @type {string}
     * @memberof EmaopayCredentials
     */
    token?: string;
}

/**
 * Check if a given object implements the EmaopayCredentials interface.
 */
export function instanceOfEmaopayCredentials(value: object): boolean {
    return true;
}

export function EmaopayCredentialsFromJSON(json: any): EmaopayCredentials {
    return EmaopayCredentialsFromJSONTyped(json, false);
}

export function EmaopayCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayCredentials {
    if (json == null) {
        return json;
    }
    return {
        
        'tmpSecretId': json['tmpSecretId'] == null ? undefined : json['tmpSecretId'],
        'tmpSecretKey': json['tmpSecretKey'] == null ? undefined : json['tmpSecretKey'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function EmaopayCredentialsToJSON(value?: EmaopayCredentials | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tmpSecretId': value['tmpSecretId'],
        'tmpSecretKey': value['tmpSecretKey'],
        'token': value['token'],
    };
}

