/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayCreateMerchantParams
 */
export interface EmaopayCreateMerchantParams {
    /**
     * 
     * @type {string}
     * @memberof EmaopayCreateMerchantParams
     */
    name: string;
}

/**
 * Check if a given object implements the EmaopayCreateMerchantParams interface.
 */
export function instanceOfEmaopayCreateMerchantParams(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function EmaopayCreateMerchantParamsFromJSON(json: any): EmaopayCreateMerchantParams {
    return EmaopayCreateMerchantParamsFromJSONTyped(json, false);
}

export function EmaopayCreateMerchantParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayCreateMerchantParams {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function EmaopayCreateMerchantParamsToJSON(value?: EmaopayCreateMerchantParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

