/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayQrCode
 */
export interface EmaopayQrCode {
    /**
     * 
     * @type {string}
     * @memberof EmaopayQrCode
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof EmaopayQrCode
     */
    content?: string;
    /**
     * 
     * @type {Date}
     * @memberof EmaopayQrCode
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EmaopayQrCode
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof EmaopayQrCode
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EmaopayQrCode
     */
    merchantId?: string;
    /**
     * 
     * @type {string}
     * @memberof EmaopayQrCode
     */
    monitorId?: string;
    /**
     * 二维码提供商, 如: wechat, alipay
     * @type {string}
     * @memberof EmaopayQrCode
     */
    provider?: string;
    /**
     * 解锁时间, unix时间戳, 0表示未锁定
     * @type {number}
     * @memberof EmaopayQrCode
     */
    unlockAt?: number;
    /**
     * 
     * @type {Date}
     * @memberof EmaopayQrCode
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the EmaopayQrCode interface.
 */
export function instanceOfEmaopayQrCode(value: object): boolean {
    return true;
}

export function EmaopayQrCodeFromJSON(json: any): EmaopayQrCode {
    return EmaopayQrCodeFromJSONTyped(json, false);
}

export function EmaopayQrCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayQrCode {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'content': json['content'] == null ? undefined : json['content'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'monitorId': json['monitorId'] == null ? undefined : json['monitorId'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'unlockAt': json['unlockAt'] == null ? undefined : json['unlockAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function EmaopayQrCodeToJSON(value?: EmaopayQrCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'content': value['content'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'id': value['id'],
        'merchantId': value['merchantId'],
        'monitorId': value['monitorId'],
        'provider': value['provider'],
        'unlockAt': value['unlockAt'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

