/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayLoginResponse
 */
export interface EmaopayLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof EmaopayLoginResponse
     */
    token?: string;
}

/**
 * Check if a given object implements the EmaopayLoginResponse interface.
 */
export function instanceOfEmaopayLoginResponse(value: object): boolean {
    return true;
}

export function EmaopayLoginResponseFromJSON(json: any): EmaopayLoginResponse {
    return EmaopayLoginResponseFromJSONTyped(json, false);
}

export function EmaopayLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function EmaopayLoginResponseToJSON(value?: EmaopayLoginResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

