/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmaopayQrCode } from './EmaopayQrCode';
import {
    EmaopayQrCodeFromJSON,
    EmaopayQrCodeFromJSONTyped,
    EmaopayQrCodeToJSON,
} from './EmaopayQrCode';

/**
 * 
 * @export
 * @interface EmaopayPagedResponseEmaopayQrCode
 */
export interface EmaopayPagedResponseEmaopayQrCode {
    /**
     * 
     * @type {Array<EmaopayQrCode>}
     * @memberof EmaopayPagedResponseEmaopayQrCode
     */
    data?: Array<EmaopayQrCode>;
    /**
     * 
     * @type {number}
     * @memberof EmaopayPagedResponseEmaopayQrCode
     */
    total?: number;
}

/**
 * Check if a given object implements the EmaopayPagedResponseEmaopayQrCode interface.
 */
export function instanceOfEmaopayPagedResponseEmaopayQrCode(value: object): boolean {
    return true;
}

export function EmaopayPagedResponseEmaopayQrCodeFromJSON(json: any): EmaopayPagedResponseEmaopayQrCode {
    return EmaopayPagedResponseEmaopayQrCodeFromJSONTyped(json, false);
}

export function EmaopayPagedResponseEmaopayQrCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayPagedResponseEmaopayQrCode {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(EmaopayQrCodeFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function EmaopayPagedResponseEmaopayQrCodeToJSON(value?: EmaopayPagedResponseEmaopayQrCode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(EmaopayQrCodeToJSON)),
        'total': value['total'],
    };
}

