/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayCreateQrCodeParams
 */
export interface EmaopayCreateQrCodeParams {
    /**
     * 
     * @type {Array<string>}
     * @memberof EmaopayCreateQrCodeParams
     */
    imageKeys?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EmaopayCreateQrCodeParams
     */
    merchantId?: string;
    /**
     * 
     * @type {string}
     * @memberof EmaopayCreateQrCodeParams
     */
    monitorId?: string;
}

/**
 * Check if a given object implements the EmaopayCreateQrCodeParams interface.
 */
export function instanceOfEmaopayCreateQrCodeParams(value: object): boolean {
    return true;
}

export function EmaopayCreateQrCodeParamsFromJSON(json: any): EmaopayCreateQrCodeParams {
    return EmaopayCreateQrCodeParamsFromJSONTyped(json, false);
}

export function EmaopayCreateQrCodeParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayCreateQrCodeParams {
    if (json == null) {
        return json;
    }
    return {
        
        'imageKeys': json['imageKeys'] == null ? undefined : json['imageKeys'],
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'monitorId': json['monitorId'] == null ? undefined : json['monitorId'],
    };
}

export function EmaopayCreateQrCodeParamsToJSON(value?: EmaopayCreateQrCodeParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'imageKeys': value['imageKeys'],
        'merchantId': value['merchantId'],
        'monitorId': value['monitorId'],
    };
}

