/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayMonitorMessage
 */
export interface EmaopayMonitorMessage {
    /**
     * 
     * @type {string}
     * @memberof EmaopayMonitorMessage
     */
    content?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmaopayMonitorMessage
     */
    handled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmaopayMonitorMessage
     */
    monitorId?: string;
    /**
     * 
     * @type {string}
     * @memberof EmaopayMonitorMessage
     */
    packageName?: string;
    /**
     * 
     * @type {number}
     * @memberof EmaopayMonitorMessage
     */
    timestamp?: number;
}

/**
 * Check if a given object implements the EmaopayMonitorMessage interface.
 */
export function instanceOfEmaopayMonitorMessage(value: object): boolean {
    return true;
}

export function EmaopayMonitorMessageFromJSON(json: any): EmaopayMonitorMessage {
    return EmaopayMonitorMessageFromJSONTyped(json, false);
}

export function EmaopayMonitorMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayMonitorMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'handled': json['handled'] == null ? undefined : json['handled'],
        'monitorId': json['monitorId'] == null ? undefined : json['monitorId'],
        'packageName': json['packageName'] == null ? undefined : json['packageName'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function EmaopayMonitorMessageToJSON(value?: EmaopayMonitorMessage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'handled': value['handled'],
        'monitorId': value['monitorId'],
        'packageName': value['packageName'],
        'timestamp': value['timestamp'],
    };
}

