/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmaopayCredentials } from './EmaopayCredentials';
import {
    EmaopayCredentialsFromJSON,
    EmaopayCredentialsFromJSONTyped,
    EmaopayCredentialsToJSON,
} from './EmaopayCredentials';

/**
 * 
 * @export
 * @interface EmaopayUploadCredits
 */
export interface EmaopayUploadCredits {
    /**
     * 存储桶名
     * @type {string}
     * @memberof EmaopayUploadCredits
     */
    bucket?: string;
    /**
     * 临时证书
     * @type {EmaopayCredentials}
     * @memberof EmaopayUploadCredits
     */
    credentials?: EmaopayCredentials;
    /**
     * 证书有效的时间，以 iso8601 格式的 UTC 时间表示
     * 注意：此字段可能返回 null，表示取不到有效值。
     * @type {string}
     * @memberof EmaopayUploadCredits
     */
    expiration?: string;
    /**
     * 临时证书有效的时间，返回 Unix 时间戳，精确到秒
     * @type {number}
     * @memberof EmaopayUploadCredits
     */
    expiredTime?: number;
    /**
     * 区域
     * @type {string}
     * @memberof EmaopayUploadCredits
     */
    region?: string;
}

/**
 * Check if a given object implements the EmaopayUploadCredits interface.
 */
export function instanceOfEmaopayUploadCredits(value: object): boolean {
    return true;
}

export function EmaopayUploadCreditsFromJSON(json: any): EmaopayUploadCredits {
    return EmaopayUploadCreditsFromJSONTyped(json, false);
}

export function EmaopayUploadCreditsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayUploadCredits {
    if (json == null) {
        return json;
    }
    return {
        
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
        'credentials': json['credentials'] == null ? undefined : EmaopayCredentialsFromJSON(json['credentials']),
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'expiredTime': json['expiredTime'] == null ? undefined : json['expiredTime'],
        'region': json['region'] == null ? undefined : json['region'],
    };
}

export function EmaopayUploadCreditsToJSON(value?: EmaopayUploadCredits | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bucket': value['bucket'],
        'credentials': EmaopayCredentialsToJSON(value['credentials']),
        'expiration': value['expiration'],
        'expiredTime': value['expiredTime'],
        'region': value['region'],
    };
}

