/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayCreateOrderParams
 */
export interface EmaopayCreateOrderParams {
    /**
     * 金额
     * @type {string}
     * @memberof EmaopayCreateOrderParams
     */
    amount?: string;
    /**
     * 商户 Id
     * @type {string}
     * @memberof EmaopayCreateOrderParams
     */
    merchantId?: string;
    /**
     * 商户订单号, 对商户而言是唯一的
     * @type {string}
     * @memberof EmaopayCreateOrderParams
     */
    merchantTradeNo?: string;
    /**
     * 回调地址
     * @type {string}
     * @memberof EmaopayCreateOrderParams
     */
    notifyURL?: string;
    /**
     * 支付方式
     * @type {string}
     * @memberof EmaopayCreateOrderParams
     */
    paymentMethod?: string;
    /**
     * 产品 Id
     * @type {string}
     * @memberof EmaopayCreateOrderParams
     */
    productId?: string;
    /**
     * 支付成功后的跳转地址
     * @type {string}
     * @memberof EmaopayCreateOrderParams
     */
    returnURL?: string;
    /**
     * 签名
     * @type {string}
     * @memberof EmaopayCreateOrderParams
     */
    signature?: string;
    /**
     * 用户 Id, 可为空，如果是匿名用户，那么就为空
     * @type {string}
     * @memberof EmaopayCreateOrderParams
     */
    userId?: string;
}

/**
 * Check if a given object implements the EmaopayCreateOrderParams interface.
 */
export function instanceOfEmaopayCreateOrderParams(value: object): boolean {
    return true;
}

export function EmaopayCreateOrderParamsFromJSON(json: any): EmaopayCreateOrderParams {
    return EmaopayCreateOrderParamsFromJSONTyped(json, false);
}

export function EmaopayCreateOrderParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayCreateOrderParams {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'merchantId': json['merchantId'] == null ? undefined : json['merchantId'],
        'merchantTradeNo': json['merchantTradeNo'] == null ? undefined : json['merchantTradeNo'],
        'notifyURL': json['notifyURL'] == null ? undefined : json['notifyURL'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : json['paymentMethod'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'returnURL': json['returnURL'] == null ? undefined : json['returnURL'],
        'signature': json['signature'] == null ? undefined : json['signature'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function EmaopayCreateOrderParamsToJSON(value?: EmaopayCreateOrderParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'merchantId': value['merchantId'],
        'merchantTradeNo': value['merchantTradeNo'],
        'notifyURL': value['notifyURL'],
        'paymentMethod': value['paymentMethod'],
        'productId': value['productId'],
        'returnURL': value['returnURL'],
        'signature': value['signature'],
        'userId': value['userId'],
    };
}

