/* tslint:disable */
/* eslint-disable */
/**
 * EmaoPay API
 * EmaoPay API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@emaopay.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmaopayCreateNewMonitorParams
 */
export interface EmaopayCreateNewMonitorParams {
    /**
     * 
     * @type {string}
     * @memberof EmaopayCreateNewMonitorParams
     */
    merchantId: string;
}

/**
 * Check if a given object implements the EmaopayCreateNewMonitorParams interface.
 */
export function instanceOfEmaopayCreateNewMonitorParams(value: object): boolean {
    if (!('merchantId' in value)) return false;
    return true;
}

export function EmaopayCreateNewMonitorParamsFromJSON(json: any): EmaopayCreateNewMonitorParams {
    return EmaopayCreateNewMonitorParamsFromJSONTyped(json, false);
}

export function EmaopayCreateNewMonitorParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmaopayCreateNewMonitorParams {
    if (json == null) {
        return json;
    }
    return {
        
        'merchantId': json['merchantId'],
    };
}

export function EmaopayCreateNewMonitorParamsToJSON(value?: EmaopayCreateNewMonitorParams | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'merchantId': value['merchantId'],
    };
}

